import numpy as np
import random
MOVER_CAPACITY = 3
BASE_STATION_CAPACITY = 1
CAP_STATION_CAPACITY = 2
RING_STATION_CAPACITY = 2
STORAGE_CAPACITY = 24
REPAIRMEN_CAPACITY = 3
DESTINATION_CAPACITY = 1
# stations location
BASE_LOCATION = [np.array([0, 0]),np.array([14, 0]), np.array([0, 0]),np.array([14, 0])]
RING_LOCATION = [np.array([2, 4]),np.array([4, 7]),np.array([7, 4]),np.array([10, 7])]
RING_LOCATION2 = np.array([11, 4])
RING_LOCATION3 = np.array([15, 15])  #gibts nicht
CAP_LOCATION = [np.array([0, 8]),np.array([14, 8]), np.array([5, 2]), np.array([10, 2])]
CAP_LOCATION2 = np.array([13, 5])
CAP_LOCATION3 = np.array([20, 20])  #gibts nicht
DEL_LOCATION = np.array([7, 8]) # only one
# mover init location
MOVER_LOCATION = [np.array([0, 0]),np.array([0, 0]), np.array([1, 0]),np.array([1, 0]), np.array([2, 0]),np.array([2, 0]), np.array([0, 0]), np.array([1, 0]),np.array([2, 0]),np.array([0, 0]), np.array([1, 0]),np.array([2, 0])]
MOVER_LOCATION2 = np.array([1, 0])
MOVER_LOCATION3 = np.array([2, 0])
TIME_TO_PICK_UP = (6, 2)
# repairman init location
REPAIRMEN_LOCATION = np.array([7, 0])
REPAIR_TIME = (110, 10) #120
# Products colors
#3 base colors
#TODO: Überlegen wie viele Farben sinnig sind..
b = ["Black", "Red", "Grey"]
#5 ring colors
r = ["Blue", "Red", "Green", "Orange", "Yellow"]
#2 cap colors
c = ["Black", "Grey"]
# Base Station
TIME_TO_CHANGE_PROC_TYPE_BS = (75 , 5) #ursprünglich 100
MEAN_TIME_TO_FAILURE_BS = 1/random.randint(600,1000)
PROC_TIME_BASE = [(7.5, 2.5)]
PROC_TYPE_INIT_BS = random.sample(b,3)
# Ring Station
TIME_TO_CHANGE_PROC_TYPE_RS = (75, 5)
MEAN_TIME_TO_FAILURE_RS = 1/random.randint(600,1000)
PROC_TIME_RING = [(50, 10), (100, 10), (150, 10)]
PROC_TYPE_INIT_RS = random.sample(r, 3)
# Cap Station
PROC_TYPE_INIT_CS = random.sample(c,1)
PROC_TIME_CAP = [(20, 5)]
TIME_TO_CHANGE_PROC_TYPE_CS = (75, 5)
MEAN_TIME_TO_FAILURE_CS = 1/random.randint(600,1000)
# Products

PRODUCT_CC3_1 = {"proc_steps": "cc3", "base": ["BLACK"], "ring": ["GREEN", "ORANGE", "YELLOW"], "cap": ["RED"], "points": 30}
PRODUCT_CC2_1 = {"proc_steps": "cc2", "base": ["BLACK"], "ring": ["GREEN", "ORANGE"], "cap": ["RED"], "points": 20}
PRODUCT_CC1_1 = {"proc_steps": "cc1","base": ["BLACK"], "ring": ["GREEN"], "cap": ["RED"], "points": 10}
PRODUCT_CC0_1 = {"proc_steps": "cc0","base": ["BLACK"], "cap": ["RED"], "points": 5}
PRODUCT_CC3_2 = {"base": ["RED"], "ring": ["BLUE", "RED", "BLACK"], "cap": ["GREEN"], "points": 30}
PRODUCT_CC2_2 = {"base": ["RED"], "ring": ["BLUE", "RED"], "cap": ["GREEN"], "points": 20}
PRODUCT_CC1_2 = {"base": ["RED"], "ring": ["BLUE"], "cap": ["GREEN"], "points": 10}
PRODUCT_CC0_2 = {"base": ["RED"], "cap": ["BLUE"], "points": 5}
PRODUCT_CC3_3 = {"base": ["BLACK"], "ring": ["GREEN", "BLUE", "GREEN"], "cap": ["BLUE"], "points": 30}
PRODUCT_CC2_3 = {"base": ["BLACK"], "ring": ["GREEN", "BLUE"], "cap": ["BLUE"], "points": 20}
PRODUCT_CC1_3 = {"base": ["BLACK"], "ring": ["GREEN"], "cap": ["RED"], "points": 10}
PRODUCT_CC0_3 = {"base": ["BLACK"], "cap": ["BLUE"], "points": 5}
MEAN_TIME_TO_FAILURE = 1/250
#del_station
PROC_TIME_DEL = (30, 10)

RANDOM_CHOICE_10 = [[{'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 660}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 660}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Yellow'], 'cap': ['Black'], 'points': 10, 'time': 695}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Orange'], 'cap': ['Grey'], 'points': 5, 'time': 644}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 661}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 760}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 709}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Orange'], 'cap': ['Grey'], 'points': 5, 'time': 644}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 760}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Orange'], 'cap': ['Grey'], 'points': 5, 'time': 644}],
    [{'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 663}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 810}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Black'], 'points': 5, 'time': 624}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Green', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 665}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 995}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 919}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 810}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Green', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 665}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 810}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Grey'], 'points': 5, 'time': 704}],
    [{'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Yellow'], 'cap': ['Black'], 'points': 5, 'time': 794}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Blue', 'Orange'], 'cap': ['Black'], 'points': 10, 'time': 635}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 821}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Green', 'Blue', 'Orange'], 'cap': ['Black'], 'points': 20, 'time': 870}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 565}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Blue', 'Orange'], 'cap': ['Black'], 'points': 10, 'time': 635}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 821}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Red', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 532}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Orange', 'Blue', 'Yellow'], 'cap': ['Black'], 'points': 20, 'time': 753}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 821}],
    [{'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 559}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Yellow', 'Red', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 678}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 1018}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Yellow', 'Red', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 678}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 985}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Yellow'], 'cap': ['Black'], 'points': 5, 'time': 1002}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Yellow', 'Red', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 678}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Blue', 'Red', 'Yellow'], 'cap': ['Grey'], 'points': 20, 'time': 603}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Yellow', 'Red', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 678}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 559}]]

RANDOM_CHOICE_20 = [[{'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 986}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Blue', 'ORANGE'], 'cap': ['Grey'], 'points': 10, 'time': 499}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['ORANGE'], 'cap': ['Black'], 'points': 5, 'time': 1487}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 410}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Yellow', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 930}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Yellow', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 930}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Yellow', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 930}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Yellow', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 930}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Yellow', 'Green'], 'cap': ['Grey'], 'points': 10, 'time': 628}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 410}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 410}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 986}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Blue', 'ORANGE', 'Yellow'], 'cap': ['Black'], 'points': 20, 'time': 386}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Yellow', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 930}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Green', 'ORANGE', 'Yellow'], 'cap': ['Grey'], 'points': 20, 'time': 607}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Yellow', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 930}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Yellow', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 930}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Blue', 'ORANGE'], 'cap': ['Grey'], 'points': 10, 'time': 499}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Yellow'], 'cap': ['Black'], 'points': 5, 'time': 532}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Yellow', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 930}],
[{'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['ORANGE'], 'cap': ['Black'], 'points': 5, 'time': 842}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 1248}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 1324}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 1248}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Red', 'ORANGE', 'Yellow'], 'cap': ['Black'], 'points': 20, 'time': 722}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Blue', 'Red'], 'cap': ['Black'], 'points': 10, 'time': 518}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 1324}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 1324}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 789}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 1324}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 789}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 789}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['ORANGE'], 'cap': ['Black'], 'points': 5, 'time': 842}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 1324}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 1324}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Green'], 'cap': ['Grey'], 'points': 10, 'time': 296}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Red', 'Blue', 'Green'], 'cap': ['Black'], 'points': 20, 'time': 411}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 743}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 1248}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 789}],
[{'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Green', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 981}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 1159}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Yellow', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 787}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Red', 'Blue', 'Green'], 'cap': ['Black'], 'points': 20, 'time': 1019}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Yellow', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 787}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Yellow', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 787}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 494}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 494}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 926}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 494}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 494}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Yellow', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 787}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Green', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 981}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 494}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 926}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Blue', 'Red', 'Yellow'], 'cap': ['Black'], 'points': 20, 'time': 649}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 494}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 494}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 1088}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 475}],
[{'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Red', 'ORANGE'], 'cap': ['Black'], 'points': 20, 'time': 620}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 1246}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 1246}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['ORANGE', 'Yellow'], 'cap': ['Grey'], 'points': 10, 'time': 579}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 1127}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['ORANGE', 'Yellow'], 'cap': ['Grey'], 'points': 10, 'time': 579}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['ORANGE', 'Yellow'], 'cap': ['Grey'], 'points': 10, 'time': 579}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 1127}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 1246}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Red', 'ORANGE'], 'cap': ['Black'], 'points': 20, 'time': 620}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 1246}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 1246}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 1246}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 1127}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Yellow'], 'cap': ['Black'], 'points': 5, 'time': 938}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Red', 'ORANGE'], 'cap': ['Black'], 'points': 20, 'time': 620}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['ORANGE', 'Yellow'], 'cap': ['Grey'], 'points': 10, 'time': 579}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['ORANGE', 'Red', 'Green'], 'cap': ['Black'], 'points': 20, 'time': 747}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Yellow'], 'cap': ['Black'], 'points': 5, 'time': 475}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 522}],
[{'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['ORANGE'], 'cap': ['Grey'], 'points': 5, 'time': 1139}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Green', 'ORANGE', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 652}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 915}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 1263}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Green', 'ORANGE', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 652}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['ORANGE'], 'cap': ['Grey'], 'points': 5, 'time': 1139}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Yellow', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 360}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['ORANGE', 'Red'], 'cap': ['Grey'], 'points': 10, 'time': 1426}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Green', 'ORANGE', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 652}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Grey'], 'points': 5, 'time': 1036}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Red', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 370}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['ORANGE', 'Red'], 'cap': ['Grey'], 'points': 10, 'time': 1426}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['ORANGE'], 'cap': ['Grey'], 'points': 5, 'time': 1139}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Red', 'Green'], 'cap': ['Grey'], 'points': 10, 'time': 703}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Blue', 'Red'], 'cap': ['Grey'], 'points': 10, 'time': 945}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Green', 'ORANGE', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 652}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Green', 'ORANGE', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 652}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Green', 'ORANGE', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 652}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Green', 'ORANGE', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 652}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Red', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 370}]

]
RANDOM_CHOICE_20_N =[[{'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Red', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 738}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Blue', 'Yellow'], 'cap': ['Grey'], 'points': 10, 'time': 699}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Red', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 738}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 1971}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 683}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 683}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 942}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Red', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 738}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Yellow', 'Red', 'Green'], 'cap': ['Grey'], 'points': 20, 'time': 1007}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Red', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 738}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Yellow', 'Red', 'Green'], 'cap': ['Grey'], 'points': 20, 'time': 1007}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 683}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 683}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 1971}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Yellow', 'Blue', 'Green'], 'cap': ['Black'], 'points': 20, 'time': 1004}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 1090}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Blue', 'ORANGE'], 'cap': ['Black'], 'points': 20, 'time': 1593}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Red', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 738}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Yellow', 'Red', 'Green'], 'cap': ['Grey'], 'points': 20, 'time': 1007}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 942}]
,[{'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Yellow'], 'cap': ['Black'], 'points': 5, 'time': 1698}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Red', 'Blue', 'Yellow'], 'cap': ['Grey'], 'points': 20, 'time': 1522}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 1880}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Yellow', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 1488}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Yellow', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 1488}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Yellow', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 1488}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Black'], 'points': 5, 'time': 877}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Black'], 'points': 5, 'time': 877}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 1880}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['ORANGE', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 1813}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Yellow', 'Blue'], 'cap': ['Black'], 'points': 10, 'time': 674}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['ORANGE', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 1813}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['ORANGE', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 1813}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['ORANGE', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 1813}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['ORANGE', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 1813}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 1930}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Yellow'], 'cap': ['Black'], 'points': 5, 'time': 1698}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['ORANGE', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 1813}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Red', 'ORANGE', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 1621}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['ORANGE', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 1813}],
                     [{'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 1011},
                      {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Blue', 'Yellow', 'Red'], 'cap': ['Grey'],
                       'points': 20, 'time': 798},
                      {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Blue', 'Yellow', 'Red'], 'cap': ['Grey'],
                       'points': 20, 'time': 798},
                      {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['ORANGE', 'Blue'], 'cap': ['Black'],
                       'points': 10, 'time': 1516},
                      {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 1485},
                      {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 798},
                      {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 1485},
                      {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 690},
                      {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 798},
                      {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Red'], 'cap': ['Black'], 'points': 5,
                       'time': 1591},
                      {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 1485},
                      {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Blue', 'Yellow', 'Red'], 'cap': ['Grey'],
                       'points': 20, 'time': 798},
                      {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Blue', 'Yellow', 'Red'], 'cap': ['Grey'],
                       'points': 20, 'time': 798},
                      {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 798},
                      {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Blue', 'Yellow', 'Red'], 'cap': ['Grey'],
                       'points': 20, 'time': 798},
                      {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5,
                       'time': 1605},
                      {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 798},
                      {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 798},
                      {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 690},
                      {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Blue', 'Red'], 'cap': ['Black'], 'points': 10,
                       'time': 799}],
                     [{'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Green', 'ORANGE', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 1260}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Red', 'Blue'], 'cap': ['Black'], 'points': 10, 'time': 1366}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Red', 'Blue'], 'cap': ['Black'], 'points': 10, 'time': 1366}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Yellow', 'Blue', 'ORANGE'], 'cap': ['Grey'], 'points': 20, 'time': 1533}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['ORANGE'], 'cap': ['Black'], 'points': 5, 'time': 1097}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Black'], 'points': 5, 'time': 1811}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Green', 'ORANGE', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 1260}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 844}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Red', 'Blue'], 'cap': ['Black'], 'points': 10, 'time': 1366}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Yellow', 'Green'], 'cap': ['Grey'], 'points': 10, 'time': 748}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 844}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 1891}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Red', 'Blue'], 'cap': ['Black'], 'points': 10, 'time': 1366}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Yellow', 'Green'], 'cap': ['Grey'], 'points': 10, 'time': 748}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Black'], 'points': 5, 'time': 1811}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 844}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Yellow', 'Green'], 'cap': ['Grey'], 'points': 10, 'time': 748}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['ORANGE', 'Blue', 'Yellow'], 'cap': ['Grey'], 'points': 20, 'time': 982}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 844}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Yellow', 'Green'], 'cap': ['Grey'], 'points': 10, 'time': 748}],
[{'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Blue'], 'cap': ['Grey'], 'points': 5, 'time': 1727}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Blue'], 'cap': ['Grey'], 'points': 5, 'time': 1727}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['ORANGE', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 1996}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Blue'], 'cap': ['Grey'], 'points': 5, 'time': 1727}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Blue', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 1270}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 1773}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Blue'], 'cap': ['Grey'], 'points': 5, 'time': 1727}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['ORANGE', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 1996}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['ORANGE', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 1996}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 1658}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 1560}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 1560}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 1560}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['ORANGE', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 1996}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Blue', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 1270}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Black'], 'points': 5, 'time': 1895}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Blue'], 'cap': ['Grey'], 'points': 5, 'time': 1727}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Blue', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 1179}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Blue', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 1179}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Red', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 1721}]]

AUSWERTUNG_18 = [[{'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 878}, {'proc_steps': 'cc2', 'base': ['Grey'], 'ring': ['Red', 'Green'], 'cap': ['Grey'], 'points': 10, 'time': 957}, {'proc_steps': 'cc0', 'base': ['Grey'], 'cap': ['Black'], 'points': 5, 'time': 746}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 823}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 823}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Orange', 'Green', 'Yellow'], 'cap': ['Grey'], 'points': 20, 'time': 921}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Orange', 'Green', 'Yellow'], 'cap': ['Grey'], 'points': 20, 'time': 921}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Orange', 'Red'], 'cap': ['Grey'], 'points': 10, 'time': 1007}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 878}, {'proc_steps': 'cc2', 'base': ['Grey'], 'ring': ['Orange', 'Red'], 'cap': ['Black'], 'points': 10, 'time': 996}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 878}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 823}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Orange', 'Green', 'Yellow'], 'cap': ['Grey'], 'points': 20, 'time': 921}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Orange', 'Green', 'Yellow'], 'cap': ['Grey'], 'points': 20, 'time': 921}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Orange', 'Yellow', 'Red'], 'cap': ['Black'], 'points': 20, 'time': 1004}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 823}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 878}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Orange', 'Yellow', 'Red'], 'cap': ['Black'], 'points': 20, 'time': 1004}],
                 [{'proc_steps': 'cc0', 'base': ['Grey'], 'cap': ['Black'], 'points': 5, 'time': 829}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 791}, {'proc_steps': 'cc0', 'base': ['Grey'], 'cap': ['Black'], 'points': 5, 'time': 829}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 1019}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 791}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 816}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Yellow', 'Red'], 'cap': ['Black'], 'points': 10, 'time': 1005}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Yellow', 'Orange', 'Red'], 'cap': ['Black'], 'points': 20, 'time': 1015}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 1019}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 791}, {'proc_steps': 'cc0', 'base': ['Grey'], 'cap': ['Black'], 'points': 5, 'time': 829}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 742}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Black'], 'points': 5, 'time': 788}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Yellow', 'Orange', 'Red'], 'cap': ['Black'], 'points': 20, 'time': 1015}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 791}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Green', 'Red', 'Yellow'], 'cap': ['Black'], 'points': 20, 'time': 909}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Yellow', 'Orange', 'Red'], 'cap': ['Black'], 'points': 20, 'time': 1015}, {'proc_steps': 'cc0', 'base': ['Grey'], 'cap': ['Black'], 'points': 5, 'time': 829}],
                 [{'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 723}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 851}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Green', 'Orange', 'Yellow'], 'cap': ['Grey'], 'points': 20, 'time': 974}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Yellow', 'Blue', 'Green'], 'cap': ['Black'], 'points': 20, 'time': 825}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 851}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 867}, {'proc_steps': 'cc2', 'base': ['Grey'], 'ring': ['Blue', 'Green'], 'cap': ['Grey'], 'points': 10, 'time': 832}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 851}, {'proc_steps': 'cc0', 'base': ['Grey'], 'cap': ['Black'], 'points': 5, 'time': 998}, {'proc_steps': 'cc0', 'base': ['Grey'], 'cap': ['Grey'], 'points': 5, 'time': 907}, {'proc_steps': 'cc0', 'base': ['Grey'], 'cap': ['Grey'], 'points': 5, 'time': 907}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 867}, {'proc_steps': 'cc0', 'base': ['Grey'], 'cap': ['Grey'], 'points': 5, 'time': 907}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 851}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Orange', 'Blue', 'Green'], 'cap': ['Grey'], 'points': 20, 'time': 973}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 851}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 851}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 851}],
                 [{'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Orange', 'Red', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 744}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Orange', 'Red', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 744}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 897}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Yellow'], 'cap': ['Black'], 'points': 5, 'time': 960}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Orange', 'Red', 'Green'], 'cap': ['Grey'], 'points': 20, 'time': 797}, {'proc_steps': 'cc0', 'base': ['Grey'], 'cap': ['Grey'], 'points': 5, 'time': 912}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 1008}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Orange', 'Red', 'Green'], 'cap': ['Grey'], 'points': 20, 'time': 797}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Orange', 'Red', 'Green'], 'cap': ['Grey'], 'points': 20, 'time': 797}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Grey'], 'points': 5, 'time': 989}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Grey'], 'points': 5, 'time': 989}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Black'], 'points': 5, 'time': 896}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Grey'], 'points': 5, 'time': 989}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Orange', 'Red', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 744}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 897}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Orange', 'Red', 'Green'], 'cap': ['Grey'], 'points': 20, 'time': 797}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Orange', 'Red', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 744}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 732}],
                 [{'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Yellow', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 888}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Orange'], 'cap': ['Grey'], 'points': 5, 'time': 751}, {'proc_steps': 'cc2', 'base': ['Grey'], 'ring': ['Blue', 'Orange'], 'cap': ['Grey'], 'points': 10, 'time': 755}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Yellow'], 'cap': ['Black'], 'points': 10, 'time': 1018}, {'proc_steps': 'cc2', 'base': ['Grey'], 'ring': ['Blue', 'Orange'], 'cap': ['Grey'], 'points': 10, 'time': 755}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Yellow', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 888}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Yellow', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 888}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Orange'], 'cap': ['Grey'], 'points': 5, 'time': 751}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 927}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 927}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Black'], 'points': 5, 'time': 978}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 927}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Yellow'], 'cap': ['Black'], 'points': 5, 'time': 823}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Yellow'], 'cap': ['Black'], 'points': 10, 'time': 1018}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 927}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Yellow'], 'cap': ['Black'], 'points': 10, 'time': 1018}, {'proc_steps': 'cc2', 'base': ['Grey'], 'ring': ['Blue', 'Orange'], 'cap': ['Grey'], 'points': 10, 'time': 755}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 764}],
                 [{'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Orange', 'Blue'], 'cap': ['Black'], 'points': 10, 'time': 999}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Blue', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 913}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Orange', 'Red', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 781}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 795}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Blue', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 913}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 933}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 898}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 941}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Blue', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 913}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Orange', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 847}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Blue', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 913}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 795}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 795}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Orange', 'Blue', 'Green'], 'cap': ['Black'], 'points': 20, 'time': 777}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Orange', 'Blue', 'Green'], 'cap': ['Black'], 'points': 20, 'time': 777}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Blue', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 913}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 941}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Orange', 'Blue', 'Green'], 'cap': ['Black'], 'points': 20, 'time': 777}],
                 [{'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Blue', 'Orange'], 'cap': ['Black'], 'points': 10, 'time': 774}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Yellow', 'Blue', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 735}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 835}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 951}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Yellow', 'Blue', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 735}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 788}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 748}, {'proc_steps': 'cc0', 'base': ['Grey'], 'cap': ['Grey'], 'points': 5, 'time': 937}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Yellow', 'Blue', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 735}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 787}, {'proc_steps': 'cc0', 'base': ['Grey'], 'cap': ['Grey'], 'points': 5, 'time': 937}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 748}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 835}, {'proc_steps': 'cc3', 'base': ['Grey'], 'ring': ['Yellow', 'Blue', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 735}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 787}, {'proc_steps': 'cc0', 'base': ['Grey'], 'cap': ['Grey'], 'points': 5, 'time': 937}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 835}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 835}],
                 [{'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Red', 'Yellow', 'Green'], 'cap': ['Black'], 'points': 20, 'time': 971}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 785}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Orange'], 'cap': ['Grey'], 'points': 10, 'time': 991}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Orange', 'Red'], 'cap': ['Black'], 'points': 10, 'time': 881}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 785}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Red', 'Yellow', 'Green'], 'cap': ['Black'], 'points': 20, 'time': 971}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Orange', 'Red'], 'cap': ['Black'], 'points': 10, 'time': 881}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Orange', 'Red'], 'cap': ['Black'], 'points': 10, 'time': 881}, {'proc_steps': 'cc2', 'base': ['Grey'], 'ring': ['Orange', 'Yellow'], 'cap': ['Grey'], 'points': 10, 'time': 810}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Orange'], 'cap': ['Grey'], 'points': 10, 'time': 991}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Orange', 'Red'], 'cap': ['Black'], 'points': 10, 'time': 881}, {'proc_steps': 'cc0', 'base': ['Grey'], 'cap': ['Black'], 'points': 5, 'time': 878}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Blue', 'Green', 'Yellow'], 'cap': ['Black'], 'points': 20, 'time': 754}, {'proc_steps': 'cc0', 'base': ['Grey'], 'cap': ['Black'], 'points': 5, 'time': 878}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 785}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 785}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Blue', 'Green', 'Yellow'], 'cap': ['Black'], 'points': 20, 'time': 754}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Red', 'Yellow', 'Green'], 'cap': ['Black'], 'points': 20, 'time': 971}],
                 [{'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 811}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Green', 'Blue'], 'cap': ['Black'], 'points': 10, 'time': 871}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Yellow', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 914}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 811}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 855}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 855}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 811}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 811}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 811}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Yellow', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 914}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Green', 'Blue'], 'cap': ['Black'], 'points': 10, 'time': 871}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 883}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 883}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 883}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 883}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Orange', 'Blue', 'Green'], 'cap': ['Grey'], 'points': 20, 'time': 745}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Red', 'Yellow'], 'cap': ['Black'], 'points': 20, 'time': 924}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 862}],
                 [{'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Yellow', 'Green', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 831}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Yellow', 'Orange', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 971}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Blue'], 'cap': ['Grey'], 'points': 5, 'time': 827}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Green', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 797}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Green', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 797}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Blue'], 'cap': ['Grey'], 'points': 5, 'time': 827}, {'proc_steps': 'cc1', 'base': ['Grey'], 'ring': ['Yellow'], 'cap': ['Black'], 'points': 5, 'time': 993}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Green', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 797}, {'proc_steps': 'cc2', 'base': ['Grey'], 'ring': ['Red', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 919}, {'proc_steps': 'cc2', 'base': ['Grey'], 'ring': ['Red', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 919}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Yellow', 'Green', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 831}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 981}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Yellow', 'Green', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 831}, {'proc_steps': 'cc2', 'base': ['Grey'], 'ring': ['Red', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 919}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Green', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 797}, {'proc_steps': 'cc2', 'base': ['Grey'], 'ring': ['Red', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 919}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 810}, {'proc_steps': 'cc2', 'base': ['Grey'], 'ring': ['Red', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 919}]]


