import numpy as np
import random
MOVER_CAPACITY = 3
BASE_STATION_CAPACITY = 1
CAP_STATION_CAPACITY = 2
RING_STATION_CAPACITY = 2
STORAGE_CAPACITY = 24
REPAIRMEN_CAPACITY = 3
DESTINATION_CAPACITY = 1
# stations location
BASE_LOCATION = [np.array([0, 0]),np.array([14, 0])]
RING_LOCATION = [np.array([2, 4]),np.array([4, 7]),np.array([7, 4]),np.array([10, 7])]
RING_LOCATION2 = np.array([11, 4])
RING_LOCATION3 = np.array([15, 15])  #gibts nicht
CAP_LOCATION = [np.array([0, 8]),np.array([14, 8]), np.array([5, 2]), np.array([10, 2])]
CAP_LOCATION2 = np.array([13, 5])
CAP_LOCATION3 = np.array([20, 20])  #gibts nicht
DEL_LOCATION = np.array([7, 8]) # only one
# mover init location
MOVER_LOCATION = [np.array([0, 0]), np.array([1, 0]),np.array([2, 0]), np.array([0, 0]), np.array([1, 0]),np.array([2, 0])]
MOVER_LOCATION2 = np.array([1, 0])
MOVER_LOCATION3 = np.array([2, 0])
TIME_TO_PICK_UP = (2, 0.3)
# repairman init location
REPAIRMEN_LOCATION = np.array([7, 0])
REPAIR_TIME = (120, 20) #120
# Products colors
#3 base colors
#TODO: Überlegen wie viele Farben sinnig sind..
b = ["BLACK", "RED", "GREY"]
#5 ring colors
r = ["BLACK","GREEN", "RED", "YELLOW", "BLUE", "ORANGE", "GREY"]
#2 cap colors
c = ["BLACK", "GREY"]
# Base Station
TIME_TO_CHANGE_PROC_TYPE_BS = (100 , 10) #ursprünglich 100
MEAN_TIME_TO_FAILURE_BS = 1/random.randint(600,1000)
PROC_TIME_BASE = [(10, 2)]
PROC_TYPE_INIT_BS = random.sample(r,3)
# Ring Station
TIME_TO_CHANGE_PROC_TYPE_RS = (100, 10)
MEAN_TIME_TO_FAILURE_RS = 1/random.randint(600,1000)
PROC_TIME_RING = [(50, 10), (70, 10), (90, 10)]
PROC_TYPE_INIT_RS = random.sample(r, 3)
# Cap Station
PROC_TYPE_INIT_CS = random.sample(r,2)
PROC_TIME_CAP = [(20, 5)]
TIME_TO_CHANGE_PROC_TYPE_CS = (100, 10)
MEAN_TIME_TO_FAILURE_CS = 1/random.randint(600,1000)
# Products

PRODUCT_CC3_1 = {"proc_steps": "cc3", "base": ["BLACK"], "ring": ["GREEN", "ORANGE", "YELLOW"], "cap": ["RED"], "points": 30}
PRODUCT_CC2_1 = {"proc_steps": "cc2", "base": ["BLACK"], "ring": ["GREEN", "ORANGE"], "cap": ["RED"], "points": 20}
PRODUCT_CC1_1 = {"proc_steps": "cc1","base": ["BLACK"], "ring": ["GREEN"], "cap": ["RED"], "points": 10}
PRODUCT_CC0_1 = {"proc_steps": "cc0","base": ["BLACK"], "cap": ["RED"], "points": 5}
PRODUCT_CC3_2 = {"base": ["RED"], "ring": ["BLUE", "RED", "BLACK"], "cap": ["GREEN"], "points": 30}
PRODUCT_CC2_2 = {"base": ["RED"], "ring": ["BLUE", "RED"], "cap": ["GREEN"], "points": 20}
PRODUCT_CC1_2 = {"base": ["RED"], "ring": ["BLUE"], "cap": ["GREEN"], "points": 10}
PRODUCT_CC0_2 = {"base": ["RED"], "cap": ["BLUE"], "points": 5}
PRODUCT_CC3_3 = {"base": ["BLACK"], "ring": ["GREEN", "BLUE", "GREEN"], "cap": ["BLUE"], "points": 30}
PRODUCT_CC2_3 = {"base": ["BLACK"], "ring": ["GREEN", "BLUE"], "cap": ["BLUE"], "points": 20}
PRODUCT_CC1_3 = {"base": ["BLACK"], "ring": ["GREEN"], "cap": ["RED"], "points": 10}
PRODUCT_CC0_3 = {"base": ["BLACK"], "cap": ["BLUE"], "points": 5}
MEAN_TIME_TO_FAILURE = 1/250
#del_station
PROC_TIME_DEL = (30, 10)

RANDOM_CHOICE_10 = [[{'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 660}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 660}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Yellow'], 'cap': ['Black'], 'points': 10, 'time': 695}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Orange'], 'cap': ['Grey'], 'points': 5, 'time': 644}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 661}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 760}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 709}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Orange'], 'cap': ['Grey'], 'points': 5, 'time': 644}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 760}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Orange'], 'cap': ['Grey'], 'points': 5, 'time': 644}],
    [{'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 663}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 810}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Black'], 'points': 5, 'time': 624}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Green', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 665}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 995}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Orange'], 'cap': ['Black'], 'points': 5, 'time': 919}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 810}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Green', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 665}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 810}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Grey'], 'points': 5, 'time': 704}],
    [{'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Yellow'], 'cap': ['Black'], 'points': 5, 'time': 794}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Blue', 'Orange'], 'cap': ['Black'], 'points': 10, 'time': 635}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 821}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Green', 'Blue', 'Orange'], 'cap': ['Black'], 'points': 20, 'time': 870}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 565}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Blue', 'Orange'], 'cap': ['Black'], 'points': 10, 'time': 635}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 821}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Red', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 532}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Orange', 'Blue', 'Yellow'], 'cap': ['Black'], 'points': 20, 'time': 753}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 821}],
    [{'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 559}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Yellow', 'Red', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 678}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 1018}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Yellow', 'Red', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 678}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 985}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Yellow'], 'cap': ['Black'], 'points': 5, 'time': 1002}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Yellow', 'Red', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 678}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Blue', 'Red', 'Yellow'], 'cap': ['Grey'], 'points': 20, 'time': 603}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Yellow', 'Red', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 678}, {'proc_steps': 'cc0', 'base': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 559}]]

RANDOM_CHOICE_20 = [[{'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 986}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Blue', 'ORANGE'], 'cap': ['Grey'], 'points': 10, 'time': 499}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['ORANGE'], 'cap': ['Black'], 'points': 5, 'time': 1487}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 410}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Yellow', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 930}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Yellow', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 930}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Yellow', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 930}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Yellow', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 930}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Yellow', 'Green'], 'cap': ['Grey'], 'points': 10, 'time': 628}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 410}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 410}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 986}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Blue', 'ORANGE', 'Yellow'], 'cap': ['Black'], 'points': 20, 'time': 386}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Yellow', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 930}, {'proc_steps': 'cc3', 'base': ['Black'], 'ring': ['Green', 'ORANGE', 'Yellow'], 'cap': ['Grey'], 'points': 20, 'time': 607}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Yellow', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 930}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Yellow', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 930}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Blue', 'ORANGE'], 'cap': ['Grey'], 'points': 10, 'time': 499}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Yellow'], 'cap': ['Black'], 'points': 5, 'time': 532}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Yellow', 'Red'], 'cap': ['Grey'], 'points': 20, 'time': 930}],
[{'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['ORANGE'], 'cap': ['Black'], 'points': 5, 'time': 842}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 1248}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 1324}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 1248}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Red', 'ORANGE', 'Yellow'], 'cap': ['Black'], 'points': 20, 'time': 722}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Blue', 'Red'], 'cap': ['Black'], 'points': 10, 'time': 518}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 1324}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 1324}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 789}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 1324}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 789}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 789}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['ORANGE'], 'cap': ['Black'], 'points': 5, 'time': 842}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 1324}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 1324}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Red', 'Green'], 'cap': ['Grey'], 'points': 10, 'time': 296}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Red', 'Blue', 'Green'], 'cap': ['Black'], 'points': 20, 'time': 411}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 743}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Green'], 'cap': ['Grey'], 'points': 5, 'time': 1248}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 789}],
[{'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Green', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 981}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 1159}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Yellow', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 787}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Red', 'Blue', 'Green'], 'cap': ['Black'], 'points': 20, 'time': 1019}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Yellow', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 787}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Yellow', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 787}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 494}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 494}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 926}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 494}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 494}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Yellow', 'Green'], 'cap': ['Black'], 'points': 10, 'time': 787}, {'proc_steps': 'cc2', 'base': ['Green'], 'ring': ['Green', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 981}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 494}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Blue'], 'cap': ['Black'], 'points': 5, 'time': 926}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Blue', 'Red', 'Yellow'], 'cap': ['Black'], 'points': 20, 'time': 649}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 494}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 494}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 1088}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Red'], 'cap': ['Black'], 'points': 5, 'time': 475}],
[{'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Red', 'ORANGE'], 'cap': ['Black'], 'points': 20, 'time': 620}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 1246}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 1246}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['ORANGE', 'Yellow'], 'cap': ['Grey'], 'points': 10, 'time': 579}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 1127}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['ORANGE', 'Yellow'], 'cap': ['Grey'], 'points': 10, 'time': 579}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['ORANGE', 'Yellow'], 'cap': ['Grey'], 'points': 10, 'time': 579}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 1127}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 1246}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Red', 'ORANGE'], 'cap': ['Black'], 'points': 20, 'time': 620}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 1246}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 1246}, {'proc_steps': 'cc0', 'base': ['Black'], 'cap': ['Grey'], 'points': 5, 'time': 1246}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 1127}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Yellow'], 'cap': ['Black'], 'points': 5, 'time': 938}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Green', 'Red', 'ORANGE'], 'cap': ['Black'], 'points': 20, 'time': 620}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['ORANGE', 'Yellow'], 'cap': ['Grey'], 'points': 10, 'time': 579}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['ORANGE', 'Red', 'Green'], 'cap': ['Black'], 'points': 20, 'time': 747}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Yellow'], 'cap': ['Black'], 'points': 5, 'time': 475}, {'proc_steps': 'cc1', 'base': ['Green'], 'ring': ['Red'], 'cap': ['Grey'], 'points': 5, 'time': 522}],
[{'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['ORANGE'], 'cap': ['Grey'], 'points': 5, 'time': 1139}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Green', 'ORANGE', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 652}, {'proc_steps': 'cc0', 'base': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 915}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['Green'], 'cap': ['Black'], 'points': 5, 'time': 1263}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Green', 'ORANGE', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 652}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['ORANGE'], 'cap': ['Grey'], 'points': 5, 'time': 1139}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Yellow', 'Blue'], 'cap': ['Grey'], 'points': 10, 'time': 360}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['ORANGE', 'Red'], 'cap': ['Grey'], 'points': 10, 'time': 1426}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Green', 'ORANGE', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 652}, {'proc_steps': 'cc1', 'base': ['Black'], 'ring': ['Blue'], 'cap': ['Grey'], 'points': 5, 'time': 1036}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Red', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 370}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['ORANGE', 'Red'], 'cap': ['Grey'], 'points': 10, 'time': 1426}, {'proc_steps': 'cc1', 'base': ['Red'], 'ring': ['ORANGE'], 'cap': ['Grey'], 'points': 5, 'time': 1139}, {'proc_steps': 'cc2', 'base': ['Black'], 'ring': ['Red', 'Green'], 'cap': ['Grey'], 'points': 10, 'time': 703}, {'proc_steps': 'cc2', 'base': ['Red'], 'ring': ['Blue', 'Red'], 'cap': ['Grey'], 'points': 10, 'time': 945}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Green', 'ORANGE', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 652}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Green', 'ORANGE', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 652}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Green', 'ORANGE', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 652}, {'proc_steps': 'cc3', 'base': ['Green'], 'ring': ['Green', 'ORANGE', 'Blue'], 'cap': ['Black'], 'points': 20, 'time': 652}, {'proc_steps': 'cc3', 'base': ['Red'], 'ring': ['Red', 'Yellow', 'Blue'], 'cap': ['Grey'], 'points': 20, 'time': 370}],



]



